---
editor_options: 
  chunk_output_type: console
---

Threat-mismatch calculations: We estimate if the amount of funding to drivers of biodiversity loss tracks the number of species threatened by each of these drivers

```{r eval=TRUE}
# Load libraries
library(tidyverse)
library(scales)
library(ggsci)
```

```{r, eval=TRUE}
# Read in data of post-processed grants
data <- read_csv("data\\post-processed-grants-for-analysis.csv") %>%
   as.data.frame() %>%
   dplyr::select(c(1:42, 49:109, 43:48))

# data.multi <- read_csv("~/Desktop/master_output_data_analysis_v15_mutlicategories.csv") %>% as.data.frame()

# Read in data on the number of species threatened (Maxwell et al. 2016)
maxwell <- read_csv("data\\2016-maxwell et al-Table S2.csv") %>%
  as.data.frame()
```
```{r, echo = FALSE}



## Category Lists
clim.energy_cat <- names(data)[c(37,38,66:74,81)]         # climate/energy/combos/other

biodiv.bio.taxa.hab_cat <- names(data)[c(19:28,43, 30:36, 82:103)]
biodiv.bio.taxa.hab_cat_multi <- names(data.multi)[c(19:28,30:36)]

u.threat_cat <- names(data)[37:42]
u.taxa_cat <- names(data)[30:36]

all.threat_cat <- append(u.threat_cat, names(data)[66:81])
all.taxa_cat <- append(u.taxa_cat, names(data)[82:103])

u.threat_list <- c("Climate Change", 
                   "Energy & Transportation",
                   "Habitat Loss",
                   "Invasive Species",
                   "Overexploitation",
                   "Pollution")
u.taxa_list <- c("Amphibians",
                 "Birds",
                 "Fish",
                 "Invertebrates",
                 "Mammals",
                 "Plants",
                 "Reptiles")
```
```{r, echo = FALSE}
## Colors
cat_colors22 <- c("#990000", "#BF1E1E", "#993399", "#4C0099", "#000099",
                  "#2E10C3", "#3685B3", "#1AB3B3", "#8FC04F", "#09A256", 
                  "#006400", "#FFF928", "#C6C600", "#FFA200", "#CE8300", 
                  "#D0471E", "#9F8109", "#835506", "#317575", "#808080",
                  "black", "white")
barplot(1:22, col = cat_colors22, names.arg = 1:22)

cat_colors7 <- cat_colors22[c(1, 5, 20, 7, 18, 11, 19)]
barplot(1:7, col = cat_colors7)
```

## Manuscript Figures
### Figure 1: Proportion of Money vs. Species Threatened
**INSERT FIGURE CAPTION FROM MANUSCRIPT**
```{r fig-1, fig.cap='Figure 1: Proportion of Money vs. Species Threatened', fig.asp=.75, fig.align='center'}
fig.1.money_bio <- by.year.money_bio %>%
  filter(Category %in% u.threat_cat) %>%
  group_by(Category) %>%
  summarise(Total = sum(Amount))

fig.1.species <- maxwell %>% 
  dplyr::select(Category, n_species_threatened) %>%
  group_by(Category) %>%
  summarise(Total = sum(n_species_threatened)) 

rawFrame <- left_join(fig.1.money_bio, fig.1.species, by = "Category") %>%
  mutate(rawMoney = Total.x) %>%   # Total Money
  mutate(rawSpecies = Total.y) %>% # Total Species
  dplyr::select(Category, rawMoney, rawSpecies)

fig.1.data_bio <- left_join(fig.1.money_bio, fig.1.species, by = "Category") %>%
  mutate(Money = (Total.x/sum(Total.x))*100) %>%   # Percentage of Total Money
  mutate(Species = (Total.y/sum(Total.y))*100) %>% # Percentage of Total Species
  dplyr::select(Category, Money, Species) %>%
  pivot_longer(c(Money, Species), names_to = "is.Money", values_to = "Amount") %>%
  left_join(rawFrame, by = "Category") %>%
  mutate(rawMoney = ifelse(is.Money == "Species", NA, rawMoney)) %>%
  mutate(rawSpecies= ifelse(is.Money == "Money", NA, rawSpecies)) %>%
  replace_na(list(rawMoney = "", rawSpecies = "")) %>%
  unite("rawValue", rawMoney:rawSpecies, sep = "", remove = FALSE) %>%
  mutate(rawValue = as.numeric(rawValue),
         rawLabels = comma(rawValue))
fig.1.data_bio$rawLabels[c(seq(1,11,2))] <- str_glue("${round(rawFrame$rawMoney/1e6)}m")
# fig.1.data_bio$rawLabels[c(seq(2,12,2))] <- rawFrame$rawSpecies

fig.1.plot_bio <- ggplot(fig.1.data_bio, 
                      aes(fill=is.Money, 
                          y=Amount, 
                          x=Category)) + 
  geom_col(position="dodge") +
  labs(x="Threat Category", 
       y="Percentage") + 
       # title="% Money Allocated vs. % Species Threatened (IUCN) by Unique Threats") +
  scale_x_discrete(labels=u.threat_list) +
  scale_fill_manual(# values = c("#556B2F", "#8f3c36"),
                    values = alpha(c("darkgreen", "orangered4"), 0.9),
                    # values = c("#556B2F", "#708090"),
                    labels = c("Money ($USD Million)", "# Threatened Species")) +
  geom_text(position = position_dodge(width= 1), 
            aes(label = rawLabels, hjust = 0.5, vjust = -0.5), angle=0, size=6) +
  ylim(0, 50) +
  theme_minimal() +
  theme(axis.title = element_text(size = 16, face = "bold"), 
        axis.ticks.length.x = unit(.5, "cm"),
        axis.text = element_text(size = 14),
        legend.title = element_blank(),
        legend.key.size = unit(1,"cm"),
        legend.text = element_text(size = 12))

# ggsave(fig.1.plot_bio, filename = "~/Columbia E3B/Conservation Group/Output V15.2/Figures/money_species_comparison.png", width=15, height=7,dpi = 300)

fig.1.plot_bio
```

