---
editor_options: 
  chunk_output_type: console
---


# Network Analysis

Figure 4: Threats Network Analysis
The code presented here for Figure 4 generates the pie charts for each threat category that can be seen in the full network analysis figure. The actual network analysis was conducted separately, in **WHERE WAS THIS CONDUCTED?**.

Threat Category Overlap
```{r, include=FALSE}
threat.net1 <- data.multi_bio %>%
  filter(Year.Authorized < 2017) %>%
  filter(Year.Authorized != 2002) %>%
  dplyr::select(cat_threat_climate:cat_threat_pollution)
threat.net1 <- map2_df(threat.net1, colnames(threat.net1), ~  c(NA, .y)[.x +1]) # Change the binary 1 values into the column heaers
threat.net2 <- data.multi_bio %>%
  filter(Year.Authorized < 2017) %>%
  filter(Year.Authorized != 2002) %>%
  dplyr::select(Grant.Amount, Num.Thr)
threat.net3 <- bind_cols(threat.net2, threat.net1) # Join the column-header data with the grant amount/number of threats per grant

threat.net3 <- threat.net3 %>%
  filter(Num.Thr != 0 & Num.Thr <= 2) %>%
  unite("z", sep = ",", cat_threat_climate:cat_threat_pollution, na.rm = TRUE, remove = FALSE) %>% # Bring together all columns into a single column, separate contents by a comma
  dplyr::select(Grant.Amount, Num.Thr, z) %>%
  separate(z, sep = ",", c("A", "B")) %>% # Break united column into two
  mutate(B = if_else(is.na(B), A, B)) %>% # Have all NA's = Column A
  mutate(A = case_when(
      A == "cat_threat_climate" ~ "Climate Change",
      A == "cat_threat_energytransport" ~ "Energy & Transportation",
      A == "cat_threat_habitat" ~ "Habitat Loss",
      A == "cat_threat_inv_spec" ~ "Invasive Species",
      A == "cat_threat_overexp" ~ "Overexploitation",
      A == "cat_threat_pollution" ~ "Pollution")) %>%
  mutate(B = case_when(
      B == "cat_threat_climate" ~ "Climate Change",
      B == "cat_threat_energytransport" ~ "Energy & Transportation",
      B == "cat_threat_habitat" ~ "Habitat Loss",
      B == "cat_threat_inv_spec" ~ "Invasive Species",
      B == "cat_threat_overexp" ~ "Overexploitation",
      B == "cat_threat_pollution" ~ "Pollution")) %>%
  group_by(A, B) %>% # group by the combinations between column A and column B, which contain one or two threats
  summarize(n = sum(Grant.Amount)) %>%
  filter(A != B) %>%
  ungroup() %>%
  mutate(p = n/sum(n))

# write_csv(threat.net3, "~/Columbia E3B/Conservation Group/Output V15.2/Tables/threat_overlap_bio.csv")

threat.net.fig <- threat.net3 %>%
  ggplot(aes(x = A, y = B)) +
  geom_tile(aes(fill = log10(n)), color = "black") +
  geom_text(aes(label = n, fontface = "bold"), color = "white") +
  scale_fill_gradient(low = "lightgray", high = "black") +
  theme_bw() +
  labs(x="",
       y = "",
       title = "Amount of Money ($USD) in Single and Paired Threat Categories") +
  theme(legend.position = "none",
        panel.grid.major = element_blank())

threat.net.fig
```

## Pie Charts
```{r}
blank_theme <- theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.border = element_blank(),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        plot.title=element_text(size=14, face="bold"))
```

