--- 
knit: "bookdown::render_book"
title: "Conservation funding does not track drivers of biodiversity loss"
author: Vijay Ramesh<sup>1*</sup>, Jay Schoen<sup>1</sup>, Michael Levin<sup>1</sup>, Pratik Dubal<sup>2</sup>, Rochelle Thomas<sup>1</sup>, Sebastian Heilpern<sup>1</sup>, Jared Meek<sup>1</sup>, Pooja Choksi<sup>1</sup>, Don J Melnick<sup>1</sup>, Sara Kross<sup>1</sup>"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    fig_caption: yes
#bibliography: [refs.bib]
biblio-style: apalike
link-citations: yes
github-repo: vjjan91/conservation-spending
description: "Conservation funding does not track drivers of biodiversity loss"
---

# Introduction  

This is the `bookdown` version of a repository that contains code and analyses associated with Ramesh et. al. (in review). 

## Attribution

Please contact the following in case of interest in the project.

- Vijay Ramesh (lead author)
    - PhD student, Columbia University

## Data access

The following files are required to reproduce our analysis.

- all-grants.csv: A sheet containing all grant data.
- list-of-preprocessing-phrases.csv: A sheet containing phrases which need to removed before classification.
- list-of-keywords.csv: A sheet containing keywords which will be used to perform the rule-based classification.
- list-of-stopwords.csv: A sheet containing stopwords, which need to be used to post-process and filter the classification results.

## Data processing

The data processing for this project is described in the following sections. Navigate through them using the links in the sidebar.

## Affiliations

<sup>1</sup>Department of Ecology, Evolution and Environmental Biology, Columbia University, 1200 Amsterdam Avenue, New York, NY 10027.

<sup>2</sup>Department of Computer Science, Columbia University, New York, NY 10027.

<sup>*</sup>Corresponding author. Email: vr2352@columbia.edu 

